name: Docker Image CI

on:
  push:
    branches: [ "main" ]


env:
  tag: ${{ vars.DOCKERHUB_USERNAME }}/timhunterdev:latest
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:

  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with: 
          github_token: ${{ env.token }}
          fetch_all_tags: true
      - name: Set tag
        id: set_tag
        run: |
          if [ ${{ steps.tag_version.outputs.new_tag == '' }} ]
          then
            echo "tag=${{ env.tag }},${{ vars.DOCKERHUB_USERNAME }}/timhunterdev:${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ env.tag }}" >> "$GITHUB_OUTPUT"
          fi
  docker:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - run: echo ${{ needs.tag.outputs.tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ needs.tag.outputs.tag }}